### ISSUE TITLE
ee域名不可以备案呀

### ISSUE THREAD

**Issue by qyccode** [willin/beian-domain#2]
前几天刚试过，客服MM说ee域名不支持备案的

**Comment by willin** [comment]
换个正常的服务商进行备案。以工信部为准。

**Comment by qyccode** [comment]
2018年新规，国别域名除了cn其他的都不能备了，hk也不行😂

**Comment by willin** [comment]
并没有吧，如果有的话这个列表上应该没有这些后缀了，工信部依然可以查到这些支持的列表。我刚更新过。

我自己的 .gg 域名也是今年备案的。

**Comment by qyccode** [comment]
我问过阿里云和网硕两家都不可以，那你是从哪里备的呢，我去问问

**Comment by willin** [comment]
我从阿里云。。。

**Comment by willin** [comment]
那你试着带一个别的域名，把这个放在第二位。

比如 .wang + 你的 .ee

**Comment by qyccode** [comment]
不行，试过了，阿里云妹子打电话过来跟我说的，不给过😞

**Comment by willin** [comment]
这是什么新政策？ 不给过就要工信部明确的批文。。。
至少目前来看 工信部的列表上是允许的，你可以到官网上查一下这个列表

**Comment by willin** [comment]
http://xn--eqrt2g.xn--vuq861b/

**Comment by qyccode** [comment]
列表上也是没有的😢，只能等啥时候国内公司代理了
